version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: container-technologies:v1.0.0
    container_name: container-technologies
    restart: always
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production